image_width = 1000
image_height = 1000
rotate = 0
approximation_order = 0
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = false
auto_adjust_iterations = true
remove_centre = true
export = "png"

glitch_tolerance = 1.4e-6

probe_sampling = 3

data_storage_interval = 10

valid_iteration_frame_multiplier = 0.25
valid_iteration_probe_multiplier = 0.02

experimental = false 