image_width = 5000
image_height = 4000
rotate = 0
approximation_order = 4
glitch_percentage = 0.001
frames = 1
frame_offset = 0
zoom_scale = 2.0
display_glitches = true
auto_adjust_iterations = true
remove_centre = false
export = "png"

glitch_tolerance = 1.4e-6

probe_sampling = 15

data_storage_interval = 100

valid_iteration_frame_multiplier = 0.10
valid_iteration_probe_multiplier = 0.01

experimental = true  

analytic_derivative = false
jitter = false