real = "-0.830318426756930535531099808020505917269245805921004150175868035998275603391204653742048941247393836377732564548614919411670186592621250218710862537263527467176096878635"
imag = "0.236124763966807803633078563258826335471324421243654563981105588585308329260401683882807304591519898997908926705042948175705739463429613061221725074527054934352193757268"
zoom = "5.81470979436E135"
iterations = 20000
