real = "-1.9990959962659111838532086240451464723873699879106041072875027138225861729613819461216022699999999999999999999999"
imag = "0.0000002758071979815309980117897130508770848629719975198765589767776483289612775591171197799999999999999999999999"
zoom = "1.55413511378E85"
iterations = 12000