real = "-1.7685304554715107439359975226423287998937254896566074423088827415719065562223946222490318219590860313620613389226996388e+00"
imag = "5.9445386042946892550190097831583153039526746987365071641624831873576346016435037438597231970921541448697901394734283301e-03"
zoom = "5.9680811401822433E112"
iterations = 250000