real = "-1.7692026523595072889383857467776111524931174128810441858206091009582682358361714060565188845736378999999999999999999700"
imag = "-0.0569076698576771144575618191177937971946160499670677653396147999149822235591500415257488642677904400000000000000000000"
zoom = "3.34680029051E46"
iterations = 275250