real = "-1.999095996265911183853208624045146472387369987910604107287502713822586172961381946121551866831936458883511e+00"
imag = "2.758071979815309980117897130508770848629719975198765589767776483289612775591171065536367492835368050791947e-07"
zoom = "3.10827E85"
iterations = 12000