real = "-1.9990959962659111838532086240451464723873699879106041072875027138225861729613819461166949317647071457645e+00 "
imag = "2.7580719798153099801178971305087708486297199751987655897677764832896127755911699395081447967040433240946e-07 "
zoom = "9.71334E83"
iterations = 12000