real = "-1.9999661944503703041843468850635057967553124154072485151176192294480158424234268438137612977886891381228704640656094986435381057574477216648567249609280392009786904752451867828831e+00"
imag = "-3.0013824367909383240724973039775924987346831190773335270174257280120474975614823581185647299288414075519224186504978181625478073632495599211589676451216600697186599581586109427363e-34"
zoom = "4.09925E158"
iterations = 60000