real = "-1.1655333947333519417384501796172924714321933574886948370635079467386009660630863680482129331890021314688012579836842018076673714838362053005104217694434001399999999999999999999999999999"
imag = "-0.2271210791418481776581963677152186196245386397864896895230410088609047882859706788178588062696655554009656384215056003193835528856821046667996157018494188799999999999999999999999999999"
iterations = 200000
zoom = "5.23742497263E151"