real = "-1.76318254341162830553305389344752837380823691545596149081562559836078692832321311234952871865218128541500509084765175112358402403580276150939292881482525799999999999999999999998"
imag = "0.01301112029473539769759042139694254767421706104013814144429240560692646010846970857463228866512042416021073212703100371864075676784733995579950635855431299999999999999999999999"
zoom = "2.00000000000E148"
iterations = 60000
