real = "-0.7564832970066900239012133696820246293286165925657849586799315589448574587578730184201689267365967578772988407695603766576374269642999999999999999999999999999999"
imag = "0.0702230443937935229896215182418165999480670056421801033794136218374406257397315121084295804357309221080306391667640546316930978149999999999999999999999999999999"
zoom = "2.05204169376E126"
iterations = 238000