real = "-7.9856115902047085671716303928097401376193131347906353282929485486693248695191552968491156020599707E-1"
imag = "-1.6592962038396502368988701380724804903460653992448693870042767565846205226594618367517619118199066E-1"
zoom = "3.2782554626465212E56"
iterations = 100000
rotate = 0