real = "-1.479946223325078880202580653442563833590828874828533272328919467504501428041551458102123157715213651035545943542078167348953885787341902612509986719999999999999999999998"
imag = "0.000901397329020353980197791866197173566251566818045102411067630386488692287189049145621584436026934218763527577290631809454796618110767424580322789999999999999999999998"
zoom = "6.09716513732E141"
iterations = 45330