real = "-1.7686787211265235234445941138665366377528770515670796752057189521584944130455932091319999999999999999999999999996"
imag = "-0.0017711960190498349500389907187858417341708313481088266497454052106162475051676157999999999999999999999999999996"
zoom = "4.74284397516E80"
iterations = 2000000