real = "-0.0494700290631040937516922267273536301187457124882248793181049402326421947726869034279915499747594190000000000000000000"
imag = "-0.6747875758446753640113920531305976563347707068224034806979997947909941983454845111514208499540310299999999999999999880"
zoom = "1.00E050"
iterations = 263010






