real = "-0.749624497378761682078626204268361386845295278123640257544815714245582864796728016987502039767791356081486877471965951748581253882975777885730827532104698067397213779012974511726247624509405298147130483778736122972203130169470392874699999999999999989999999999999999999999499999999999999999980"
imag = "0.034270108740460169451729515457494748680515346724391118531748547383705957729359301718429997787132227942154534366289982005919142082076326747807809784967848438076905104018293013090695421984135743924258851663672311920874163384970654955099999999999999990000000000000000000000000000000000000000000"
zoom = "5.00E227"
iterations = 1200000




